### ISSUE TITLE
example_usage.py won't run. No module named future

### ISSUE THREAD

**Issue by frakman1** [alexmojaki/birdseye#48]
I tried this on my Mac OSX-10.12.6 Sierra
``` bash
$pip install birdseye
Requirement already satisfied: birdseye in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: asttokens in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: backports.functools-lru-cache in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: Flask in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: littleutils in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: future in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: typing in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: cheap-repr in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: flask-humanize in /usr/local/lib/python2.7/site-packages (from birdseye)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from asttokens->birdseye)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/site-packages (from Flask->birdseye)
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python2.7/site-packages (from Flask->birdseye)
Requirement already satisfied: click>=2.0 in /usr/local/lib/python2.7/site-packages (from Flask->birdseye)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/site-packages (from Flask->birdseye)
Requirement already satisfied: qualname in /usr/local/lib/python2.7/site-packages (from cheap-repr->birdseye)
Requirement already satisfied: humanize>=0.5.1 in /usr/local/lib/python2.7/site-packages (from flask-humanize->birdseye)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.4->Flask->birdseye)

$python example_usage.py
Traceback (most recent call last):
  File "example_usage.py", line 4, in <module>
    from birdseye import eye
  File "/Users/frak/git/birdseye/birdseye/birdseye/__init__.py", line 3, in <module>
    from future import standard_library
ImportError: No module named future

$pip install future
Requirement already satisfied: future in /usr/local/lib/python2.7/site-packages

$which python
/usr/bin/python

$python --version
Python 2.7.10
```

**Comment by alexmojaki** [comment]
Hm, this sounds more like your system being broken than a problem with birdseye. `future` is just the first thing that birdseye tries to import, and it's a very widely used library. Please try the following:

1. Open a Python shell.
2. Try `import future`.
3. Try importing other packages above, e.g. `asttokens`, `Flask`, `sqlalchemy`.
4. Create a new virtualenv, activate it, install birdseye, and repeat the above.

**Comment by alexmojaki** [comment]
Closing as I see no indication that this is a birdseye problem.
